python:
    - "3.7.2"	    - "3.7.2"
services: 
    - postgresql

before_script:
    - psql -c 'create database ah_groot_db;' -U postgres

install:
    - pip install -r requirements.txt	    
  
script:
    - coverage run --source='authors' manage.py test

after_success:
    - coveralls